# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 624199470975059bc66229e27fe113bbe2fd4f67a409f9c0fc46e0b4748285f4c1a4ec1b2f02839f598034dfc69ccdaa5c8027daf79251970bd86fef293893ee

test:
  secret_key_base: 919c6311ca5ad37e2cef7dd252197854c2b582ed7e9c42844cfe6453f096cb464e1614689b403a1993689c02663f4f1f9ebf8ef6831e76147e3344f5926b2bdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
